In [5]:
import numpy as np
import pandas as pd
import plotly.express as px
from scipy import stats

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
pd.set_option("display.width", 80)

NumPy: 2.5.3
Pandas: 3.0.6

### Load the Data Sets

In [3]:
df_fixtures = pd.read_csv("wc_2026_fixtures.csv")
df_teams = pd.read_csv("wc_2026_teams.csv")
df_editions = pd.read_csv("wc_all_editions.csv")
df_matches = pd.read_csv("wc_all_matches.csv")
df_scorers = pd.read_csv("wc_top_scorers.csv")

**DataFrame Detailes**

In [18]:
print(f"\nShape:\n{df_fixtures.shape}")
print(f"\nColumns:\n{df_fixtures.columns.tolist()}")
print(f"\nData types:\n{df_fixtures.dtypes}")
print("\nFirst 5 rows:")
display(df_fixtures)
print("\nInfo:")
df_fixtures.info()
print("dataframe descirebtion: ")
display(df_fixtures.describe().T)
df_fixtures.describe(include="str").T

Shape:
(104, 15)

Columns:
['group', 'stage', 'team1', 'team2', 'venue', 'city', 'country', 'date', 'kickoff_et', 'team1_confederation', 'team1_fifa_rank', 'team1_coach', 'team2_confederation', 'team2_fifa_rank', 'team2_coach']

Data types:
group                      str
stage                      str
team1                      str
team2                      str
venue                      str
city                       str
country                    str
date                       str
kickoff_et                 str
team1_confederation        str
team1_fifa_rank        float64
team1_coach                str
team2_confederation        str
team2_fifa_rank        float64
team2_coach                str
dtype: object

First 5 rows:

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,NaN,Quarter-final,QF7,QF8,NRG Stadium,Houston,USA,2026-07-11,TBD,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,Semi-final,SF1,SF2,AT&T Stadium,Arlington,USA,2026-07-14,TBD,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,Semi-final,SF3,SF4,MetLife Stadium,East Rutherford,USA,2026-07-15,TBD,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,3rd Place Match,3rd Place,3rd Place,Hard Rock Stadium,Miami,USA,2026-07-18,TBD,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,Final,Finalist 1,Finalist 2,MetLife Stadium,East Rutherford,USA,2026-07-19,TBD,NaN,NaN,NaN,NaN,NaN,NaN

Info:
<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     str
 1   stage                104 non-null    str
 2   team1                104 non-null    str
 3   team2                104 non-null    str
 4   venue                104 non-null    str
 5   city                 104 non-null    str
 6   country              104 non-null    str
 7   date                 104 non-null    str
 8   kickoff_et           104 non-null    str
 9   team1_confederation  72 non-null     str
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     str
 12  team2_confederation  72 non-null     str
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     str
dtypes: float64(2), str(13)
memory usage: 12.3 KB
dataframe descirebtion:

                 count       mean        std  min    25%   50%    75%   max
team1_fifa_rank   72.0  30.208333  24.521297  1.0   9.75  24.0  44.00  95.0
team2_fifa_rank   72.0  37.916667  23.836739  1.0  17.75  35.5  57.75  95.0

                    count unique            top freq
group                  72     12              A    6
stage                 104      7    Group Stage   72
team1                 104     80    South Korea    2
team2                 104     80   South Africa    2
venue                 104     16   AT&T Stadium   16
city                  104     16      Arlington   16
country               104      3            USA   80
date                  104     34     2026-06-26    8
kickoff_et            104     14            TBD   32
team1_confederation    72      6           UEFA   28
team1_coach            72     48  Hong Myung-bo    2
team2_confederation    72      6           UEFA   20
team2_coach            72     48     Hugo Broos    2

In [ ]:
print(f"\nShape:\n{df_teams.shape}")
print(f"\nColumns:\n{df_teams.columns.tolist()}")
print(f"\nData types:\n{df_teams.dtypes}")
print("\nFirst 5 rows:")
display(df_teams.head())
print("\nInfo:")
df_teams.info()
print("dataframe descirebtion: ")
display(df_teams.describe().T)
df_teams.describe(include="str").T

In [ ]:
print(f"\nShape:\n{df_editions.shape}")
print(f"\nColumns:\n{df_editions.columns.tolist()}")
print(f"\nData types:\n{df_editions.dtypes}")
print("\nFirst 5 rows:")
display(df_editions.head())
print("\nInfo:")
df_editions.info()
print("dataframe descirebtion: ")
display(df_editions.describe().T)
df_editions.describe(include="str").T

In [ ]:
print(f"\nShape:\n{df_matches.shape}")
print(f"\nColumns:\n{df_matches.columns.tolist()}")
print(f"\nData types:\n{df_matches.dtypes}")
print("\nFirst 5 rows:")
display(df_matches.head())
print("\nInfo:")
df_matches.info()
print("dataframe descirebtion: ")
display(df_matches.describe().T)
df_matches.describe(include="str").T

In [ ]:
print(f"\nShape:\n{df_scorers.shape}")
print(f"\nColumns:\n{df_scorers.columns.tolist()}")
print(f"\nData types:\n{df_scorers.dtypes}")
print("\nFirst 5 rows:")
display(df_scorers.head())
print("\nInfo:")
df_scorers.info()
print("dataframe descirebtion: ")
display(df_scorers.describe().T)
df_scorers.describe(include="str").T

**Finding the missing values (each DataFrame sepretly)**

In [ ]:
df_fixtures.isnull().sum()
# missing values are knockout matchess

group                  32
stage                   0
team1                   0
team2                   0
venue                   0
city                    0
country                 0
date                    0
kickoff_et              0
team1_confederation    32
team1_fifa_rank        32
team1_coach            32
team2_confederation    32
team2_fifa_rank        32
team2_coach            32
dtype: int64

**Finding the duplicated values (each DataFrame sepretly)**

In [ ]:
df_fixtures.duplicated().head()
# no duplicates!

0    False
1    False
2    False
3    False
4    False
dtype: bool